version: "3.5"

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d

    php-fpm:
        build:
            context: ./docker/php
        container_name: php-fpm
        environment:
            XDEBUG_CONFIG: "remote_host=172.31.0.1"
            PHP_IDE_CONFIG: "serverName=localhost"
        volumes:
            - ./:/var/www/html
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - 4306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
          - ./docker/mysql:/var/lib/mysql
